-- AFRIVA Phase 10: SaaS billing.

CREATE TABLE billing_plan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    monthly_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    yearly_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    trial_days INTEGER NOT NULL DEFAULT 14,
    max_users INTEGER,
    max_stores INTEGER,
    max_products INTEGER,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE billing_subscription (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    deleted_at TIMESTAMPTZ,
    plan_id INTEGER NOT NULL REFERENCES billing_plan(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL DEFAULT 'trialing',
    billing_interval VARCHAR(20) NOT NULL DEFAULT 'monthly',
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trial_ends_at TIMESTAMPTZ,
    current_period_start TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    current_period_end TIMESTAMPTZ NOT NULL,
    canceled_at TIMESTAMPTZ,
    external_customer_id VARCHAR(255),
    external_subscription_id VARCHAR(255) UNIQUE
);
CREATE INDEX ix_billing_subscription_organization_id ON billing_subscription(organization_id);
CREATE INDEX ix_billing_subscription_status ON billing_subscription(status);

CREATE TABLE billing_invoice (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    deleted_at TIMESTAMPTZ,
    subscription_id INTEGER NOT NULL REFERENCES billing_subscription(id) ON DELETE RESTRICT,
    number VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    amount NUMERIC(12,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'XOF',
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ
);
CREATE INDEX ix_billing_invoice_organization_id ON billing_invoice(organization_id);
CREATE INDEX ix_billing_invoice_status ON billing_invoice(status);

CREATE TABLE billing_payment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    deleted_at TIMESTAMPTZ,
    invoice_id INTEGER NOT NULL REFERENCES billing_invoice(id) ON DELETE RESTRICT,
    amount NUMERIC(12,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'XOF',
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    provider VARCHAR(50) NOT NULL DEFAULT 'manual',
    provider_reference VARCHAR(255) UNIQUE,
    paid_at TIMESTAMPTZ
);
CREATE INDEX ix_billing_payment_organization_id ON billing_payment(organization_id);
CREATE INDEX ix_billing_payment_status ON billing_payment(status);

ALTER TABLE billing_subscription ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_invoice ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_payment ENABLE ROW LEVEL SECURITY;

CREATE POLICY billing_subscription_tenant_isolation ON billing_subscription
    USING (organization_id = NULLIF(current_setting('app.current_organization_id', true), '')::INTEGER)
    WITH CHECK (organization_id = NULLIF(current_setting('app.current_organization_id', true), '')::INTEGER);
CREATE POLICY billing_invoice_tenant_isolation ON billing_invoice
    USING (organization_id = NULLIF(current_setting('app.current_organization_id', true), '')::INTEGER)
    WITH CHECK (organization_id = NULLIF(current_setting('app.current_organization_id', true), '')::INTEGER);
CREATE POLICY billing_payment_tenant_isolation ON billing_payment
    USING (organization_id = NULLIF(current_setting('app.current_organization_id', true), '')::INTEGER)
    WITH CHECK (organization_id = NULLIF(current_setting('app.current_organization_id', true), '')::INTEGER);

ALTER TABLE billing_subscription FORCE ROW LEVEL SECURITY;
ALTER TABLE billing_invoice FORCE ROW LEVEL SECURITY;
ALTER TABLE billing_payment FORCE ROW LEVEL SECURITY;

INSERT INTO billing_plan
    (code, name, description, monthly_price, yearly_price, trial_days, max_users, max_stores, max_products)
VALUES
    ('FREE', 'Free', 'Découverte AFRIVA', 0, 0, 14, 2, 1, 100),
    ('STARTER', 'Starter', 'Petite entreprise', 15000, 150000, 14, 5, 2, 1000),
    ('BUSINESS', 'Business', 'Entreprise en croissance', 35000, 350000, 14, 15, 5, 5000),
    ('PROFESSIONAL', 'Professional', 'Gestion avancée multi-sites', 75000, 750000, 14, 50, 15, 25000),
    ('ENTERPRISE', 'Enterprise', 'Grand compte', 0, 0, 30, NULL, NULL, NULL)
ON CONFLICT (code) DO NOTHING;
