-- AFRIVA Phase 5: sales domain
-- Safe/idempotent PostgreSQL migration for tenant-aware sales tables.

CREATE TABLE IF NOT EXISTS product (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    name VARCHAR(255) NOT NULL,
    sku VARCHAR(100),
    category VARCHAR(100),
    unit VARCHAR(50) NOT NULL DEFAULT 'unit',
    unit_price NUMERIC(14,2) NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_product_organization_id ON product(organization_id);
CREATE INDEX IF NOT EXISTS ix_product_sku ON product(sku);
CREATE INDEX IF NOT EXISTS ix_product_active ON product(active);

CREATE TABLE IF NOT EXISTS sale (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    commercial_id INTEGER NOT NULL REFERENCES commercial(id) ON DELETE RESTRICT,
    client_id INTEGER REFERENCES client(id) ON DELETE RESTRICT,
    sold_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    notes TEXT,
    total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_sale_organization_id ON sale(organization_id);
CREATE INDEX IF NOT EXISTS ix_sale_commercial_id ON sale(commercial_id);
CREATE INDEX IF NOT EXISTS ix_sale_client_id ON sale(client_id);
CREATE INDEX IF NOT EXISTS ix_sale_sold_at ON sale(sold_at);
CREATE INDEX IF NOT EXISTS ix_sale_status ON sale(status);

CREATE TABLE IF NOT EXISTS sale_line (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    sale_id INTEGER NOT NULL REFERENCES sale(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE RESTRICT,
    quantity NUMERIC(14,3) NOT NULL DEFAULT 1,
    unit_price NUMERIC(14,2) NOT NULL,
    line_total NUMERIC(14,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS ix_sale_line_organization_id ON sale_line(organization_id);
CREATE INDEX IF NOT EXISTS ix_sale_line_sale_id ON sale_line(sale_id);
CREATE INDEX IF NOT EXISTS ix_sale_line_product_id ON sale_line(product_id);

CREATE TABLE IF NOT EXISTS sales_target (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    commercial_id INTEGER NOT NULL REFERENCES commercial(id) ON DELETE RESTRICT,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
    target_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uq_sales_target_org_commercial_period UNIQUE (organization_id, commercial_id, year, month)
);

CREATE INDEX IF NOT EXISTS ix_sales_target_organization_id ON sales_target(organization_id);
CREATE INDEX IF NOT EXISTS ix_sales_target_commercial_id ON sales_target(commercial_id);
CREATE INDEX IF NOT EXISTS ix_sales_target_year ON sales_target(year);
CREATE INDEX IF NOT EXISTS ix_sales_target_month ON sales_target(month);
