-- AFRIVA Phase 6: POS / cash register schema.
-- Idempotent PostgreSQL migration; all operational tables are tenant-aware.

CREATE TABLE IF NOT EXISTS store (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(100) NOT NULL,
    address VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_store_organization_id ON store(organization_id);
CREATE INDEX IF NOT EXISTS ix_store_code ON store(code);
CREATE INDEX IF NOT EXISTS ix_store_active ON store(active);

CREATE TABLE IF NOT EXISTS pos_register (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    store_id INTEGER NOT NULL REFERENCES store(id) ON DELETE RESTRICT,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS ix_pos_register_organization_id ON pos_register(organization_id);
CREATE INDEX IF NOT EXISTS ix_pos_register_store_id ON pos_register(store_id);
CREATE INDEX IF NOT EXISTS ix_pos_register_code ON pos_register(code);

CREATE TABLE IF NOT EXISTS cash_session (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    register_id INTEGER NOT NULL REFERENCES pos_register(id) ON DELETE RESTRICT,
    opened_by INTEGER NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    closed_by INTEGER REFERENCES "user"(id) ON DELETE RESTRICT,
    opened_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMPTZ,
    opening_cash NUMERIC(14,2) NOT NULL DEFAULT 0,
    closing_cash NUMERIC(14,2),
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_cash_session_status CHECK (status IN ('open','closed'))
);
CREATE INDEX IF NOT EXISTS ix_cash_session_organization_id ON cash_session(organization_id);
CREATE INDEX IF NOT EXISTS ix_cash_session_register_id ON cash_session(register_id);
CREATE INDEX IF NOT EXISTS ix_cash_session_status ON cash_session(status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_cash_session_open_register ON cash_session(register_id) WHERE status = 'open' AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS pos_sale (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    session_id INTEGER NOT NULL REFERENCES cash_session(id) ON DELETE RESTRICT,
    reference VARCHAR(100) NOT NULL UNIQUE,
    sold_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'confirmed',
    total_amount NUMERIC(14,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_pos_sale_status CHECK (status IN ('confirmed','cancelled'))
);
CREATE INDEX IF NOT EXISTS ix_pos_sale_organization_id ON pos_sale(organization_id);
CREATE INDEX IF NOT EXISTS ix_pos_sale_session_id ON pos_sale(session_id);
CREATE INDEX IF NOT EXISTS ix_pos_sale_sold_at ON pos_sale(sold_at);

CREATE TABLE IF NOT EXISTS pos_sale_line (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    sale_id INTEGER NOT NULL REFERENCES pos_sale(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES product(id) ON DELETE RESTRICT,
    quantity NUMERIC(14,3) NOT NULL,
    unit_price NUMERIC(14,2) NOT NULL,
    line_total NUMERIC(14,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_pos_sale_line_quantity CHECK (quantity > 0),
    CONSTRAINT ck_pos_sale_line_price CHECK (unit_price >= 0)
);
CREATE INDEX IF NOT EXISTS ix_pos_sale_line_organization_id ON pos_sale_line(organization_id);
CREATE INDEX IF NOT EXISTS ix_pos_sale_line_sale_id ON pos_sale_line(sale_id);
CREATE INDEX IF NOT EXISTS ix_pos_sale_line_product_id ON pos_sale_line(product_id);

CREATE TABLE IF NOT EXISTS pos_payment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    sale_id INTEGER NOT NULL REFERENCES pos_sale(id) ON DELETE CASCADE,
    method VARCHAR(30) NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    paid_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_pos_payment_amount CHECK (amount > 0),
    CONSTRAINT ck_pos_payment_method CHECK (method IN ('cash','card','mobile_money','transfer'))
);
CREATE INDEX IF NOT EXISTS ix_pos_payment_organization_id ON pos_payment(organization_id);
CREATE INDEX IF NOT EXISTS ix_pos_payment_sale_id ON pos_payment(sale_id);
