-- AFRIVA Phase 10: SaaS billing.
-- Idempotent PostgreSQL migration. No production execution is performed here.

CREATE TABLE IF NOT EXISTS billing_plan (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    monthly_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    yearly_price NUMERIC(12,2) NOT NULL DEFAULT 0,
    trial_days INTEGER NOT NULL DEFAULT 14,
    max_users INTEGER,
    max_stores INTEGER,
    max_products INTEGER,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_billing_plan_trial_days CHECK (trial_days >= 0),
    CONSTRAINT ck_billing_plan_monthly_price CHECK (monthly_price >= 0),
    CONSTRAINT ck_billing_plan_yearly_price CHECK (yearly_price >= 0)
);

CREATE TABLE IF NOT EXISTS billing_subscription (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    plan_id INTEGER NOT NULL REFERENCES billing_plan(id) ON DELETE RESTRICT,
    status VARCHAR(30) NOT NULL DEFAULT 'trialing',
    billing_interval VARCHAR(20) NOT NULL DEFAULT 'monthly',
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trial_ends_at TIMESTAMPTZ,
    current_period_start TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    current_period_end TIMESTAMPTZ NOT NULL,
    canceled_at TIMESTAMPTZ,
    external_customer_id VARCHAR(255),
    external_subscription_id VARCHAR(255) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_billing_subscription_interval CHECK (billing_interval IN ('monthly','yearly')),
    CONSTRAINT ck_billing_subscription_status CHECK (status IN ('trialing','active','canceled','expired','past_due'))
);
CREATE INDEX IF NOT EXISTS ix_billing_subscription_org_status ON billing_subscription(organization_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_billing_active_org ON billing_subscription(organization_id) WHERE status IN ('trialing','active') AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS billing_invoice (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    subscription_id INTEGER NOT NULL REFERENCES billing_subscription(id) ON DELETE RESTRICT,
    number VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    amount NUMERIC(12,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'XOF',
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    due_at TIMESTAMPTZ,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_billing_invoice_status CHECK (status IN ('open','paid','void','overdue')),
    CONSTRAINT ck_billing_invoice_amount CHECK (amount >= 0)
);
CREATE INDEX IF NOT EXISTS ix_billing_invoice_org_status ON billing_invoice(organization_id, status);

CREATE TABLE IF NOT EXISTS billing_payment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organization(id) ON DELETE RESTRICT,
    invoice_id INTEGER NOT NULL REFERENCES billing_invoice(id) ON DELETE RESTRICT,
    amount NUMERIC(12,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'XOF',
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    provider VARCHAR(50) NOT NULL DEFAULT 'manual',
    provider_reference VARCHAR(255) UNIQUE,
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT ck_billing_payment_status CHECK (status IN ('pending','succeeded','failed','refunded')),
    CONSTRAINT ck_billing_payment_amount CHECK (amount > 0)
);
CREATE INDEX IF NOT EXISTS ix_billing_payment_org_invoice ON billing_payment(organization_id, invoice_id);
